#!/usr/bin/env bash
# pb bash completion script
# Generated by 'pb completion bash'

# This script provides bash completion for the pb command.
# To use it, either:
# 1. Source it directly: source pb.bash
# 2. Copy it to your bash completions directory:
#    - Linux: /etc/bash_completion.d/
#    - macOS with Homebrew: $(brew --prefix)/etc/bash_completion.d/

_pb_completion() {
    local cur prev words cword
    _init_completion || return

    # Command hierarchy
    local commands="init put get delete root prove verify stats batch export-keys import repl completion help"
    local global_flags="--db --json --verbose --help"

    # If we're on the first word after 'pb', suggest commands
    if [[ ${cword} -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "${commands}" -- "${cur}") )
        return
    fi

    # Get the command being completed
    local cmd="${words[1]}"

    # Command-specific completions
    case "${cmd}" in
        put)
            case "${prev}" in
                --hex-key|--file-value)
                    # File completion for --file-value
                    if [[ "${prev}" == "--file-value" ]]; then
                        _filedir
                    fi
                    return
                    ;;
                *)
                    COMPREPLY=( $(compgen -W "--hex-key --file-value ${global_flags}" -- "${cur}") )
                    ;;
            esac
            ;;
        get)
            COMPREPLY=( $(compgen -W "--hex-key --version ${global_flags}" -- "${cur}") )
            ;;
        delete)
            COMPREPLY=( $(compgen -W "--hex-key ${global_flags}" -- "${cur}") )
            ;;
        prove)
            case "${prev}" in
                --output)
                    _filedir
                    return
                    ;;
                *)
                    COMPREPLY=( $(compgen -W "--hex-key --version --output ${global_flags}" -- "${cur}") )
                    ;;
            esac
            ;;
        verify)
            if [[ ${cword} -eq 2 ]]; then
                _filedir "proof"
            else
                COMPREPLY=( $(compgen -W "${global_flags}" -- "${cur}") )
            fi
            ;;
        batch)
            if [[ ${cword} -eq 2 ]]; then
                _filedir "json"
            else
                COMPREPLY=( $(compgen -W "--dry-run --skip-errors ${global_flags}" -- "${cur}") )
            fi
            ;;
        export-keys)
            case "${prev}" in
                --keys|--output)
                    _filedir
                    return
                    ;;
                --format)
                    COMPREPLY=( $(compgen -W "json csv" -- "${cur}") )
                    return
                    ;;
                --keys-format)
                    COMPREPLY=( $(compgen -W "text hex" -- "${cur}") )
                    return
                    ;;
                *)
                    COMPREPLY=( $(compgen -W "--keys --format --output --hex --version --keys-format ${global_flags}" -- "${cur}") )
                    ;;
            esac
            ;;
        import)
            case "${prev}" in
                --format)
                    COMPREPLY=( $(compgen -W "json csv" -- "${cur}") )
                    return
                    ;;
                *)
                    if [[ ${cword} -eq 2 ]]; then
                        _filedir "@(json|csv)"
                    else
                        COMPREPLY=( $(compgen -W "--format --skip-errors --validate ${global_flags}" -- "${cur}") )
                    fi
                    ;;
            esac
            ;;
        completion)
            if [[ ${cword} -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "bash zsh fish powershell" -- "${cur}") )
            fi
            ;;
        init|root|stats|repl|help)
            COMPREPLY=( $(compgen -W "${global_flags}" -- "${cur}") )
            ;;
        *)
            # For unknown commands or global context
            COMPREPLY=( $(compgen -W "${commands} ${global_flags}" -- "${cur}") )
            ;;
    esac
}

complete -F _pb_completion pb