package metrics

import (
	"sync"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

// PrometheusMetrics implements comprehensive JMT metrics collection using Prometheus
type PrometheusMetrics struct {
	// Core JMT Metrics - Counters
	commitsTotal          prometheus.Counter
	operationsTotal       *prometheus.CounterVec
	proofGenerationsTotal *prometheus.CounterVec
	hashOperationsTotal   prometheus.Counter
	dbReadsTotal          prometheus.Counter
	dbWritesTotal         prometheus.Counter
	errorsTotal           *prometheus.CounterVec
	validationFailures    prometheus.Counter

	// Histogram metrics
	commitLatency          prometheus.Histogram
	lookupLatency          prometheus.Histogram
	proofGenerationLatency prometheus.Histogram
	batchSize              prometheus.Histogram

	// Gauge metrics
	treeHeight     prometheus.Gauge
	treeNodesTotal prometheus.Gauge
	versionsStored prometheus.Gauge
	dbLiveBytes    prometheus.Gauge
	proofSizeBytes prometheus.Histogram

	// Registry for this instance
	registry *prometheus.Registry
	factory  promauto.Factory

	// Initialization
	once sync.Once
}

// NewPrometheusMetrics creates a new Prometheus metrics collector
func NewPrometheusMetrics() *PrometheusMetrics {
	return NewPrometheusMetricsWithRegistry(prometheus.DefaultRegisterer)
}

// NewPrometheusMetricsWithRegistry creates a new Prometheus metrics collector with a custom registry
func NewPrometheusMetricsWithRegistry(registerer prometheus.Registerer) *PrometheusMetrics {
	m := &PrometheusMetrics{
		factory: promauto.With(registerer),
	}
	m.initMetrics()
	return m
}

func (m *PrometheusMetrics) initMetrics() {
	m.once.Do(func() {
		// Counter metrics
		m.commitsTotal = m.factory.NewCounter(prometheus.CounterOpts{
			Name: "jmt_commits_total",
			Help: "Total number of commits to the Jellyfish Merkle Tree",
		})

		m.operationsTotal = m.factory.NewCounterVec(
			prometheus.CounterOpts{
				Name: "jmt_operations_total",
				Help: "Total number of operations by type",
			},
			[]string{"type"}, // insert, update, delete
		)

		m.proofGenerationsTotal = m.factory.NewCounterVec(
			prometheus.CounterOpts{
				Name: "jmt_proof_generations_total",
				Help: "Total number of proofs generated by type",
			},
			[]string{"type"}, // inclusion, exclusion
		)

		m.hashOperationsTotal = m.factory.NewCounter(prometheus.CounterOpts{
			Name: "jmt_hash_operations_total",
			Help: "Total number of hash computations",
		})

		m.dbReadsTotal = m.factory.NewCounter(prometheus.CounterOpts{
			Name: "jmt_db_reads_total",
			Help: "Total number of database read operations",
		})

		m.dbWritesTotal = m.factory.NewCounter(prometheus.CounterOpts{
			Name: "jmt_db_writes_total",
			Help: "Total number of database write operations",
		})

		m.errorsTotal = m.factory.NewCounterVec(
			prometheus.CounterOpts{
				Name: "jmt_errors_total",
				Help: "Total number of errors by type",
			},
			[]string{"type"},
		)

		m.validationFailures = m.factory.NewCounter(prometheus.CounterOpts{
			Name: "jmt_validation_failures_total",
			Help: "Total number of proof validation failures",
		})

		// Histogram metrics
		m.commitLatency = m.factory.NewHistogram(prometheus.HistogramOpts{
			Name:    "jmt_commit_latency_seconds",
			Help:    "Time spent on commit operations",
			Buckets: prometheus.ExponentialBuckets(0.0001, 2, 15), // 100μs to ~3.2s
		})

		m.lookupLatency = m.factory.NewHistogram(prometheus.HistogramOpts{
			Name:    "jmt_lookup_latency_seconds",
			Help:    "Time spent on lookup operations",
			Buckets: prometheus.ExponentialBuckets(0.0001, 2, 12), // 100μs to ~400ms
		})

		m.proofGenerationLatency = m.factory.NewHistogram(prometheus.HistogramOpts{
			Name:    "jmt_proof_generation_latency_seconds",
			Help:    "Time spent generating proofs",
			Buckets: prometheus.ExponentialBuckets(0.0001, 2, 13), // 100μs to ~800ms
		})

		m.batchSize = m.factory.NewHistogram(prometheus.HistogramOpts{
			Name:    "jmt_batch_size",
			Help:    "Number of operations per batch",
			Buckets: []float64{1, 5, 10, 25, 50, 100, 250, 500, 1000, 2500, 5000, 10000},
		})

		m.proofSizeBytes = m.factory.NewHistogram(prometheus.HistogramOpts{
			Name:    "jmt_proof_size_bytes",
			Help:    "Size of generated proofs in bytes",
			Buckets: prometheus.ExponentialBuckets(64, 2, 12), // 64B to ~256KB
		})

		// Gauge metrics
		m.treeHeight = m.factory.NewGauge(prometheus.GaugeOpts{
			Name: "jmt_tree_height",
			Help: "Current height of the Jellyfish Merkle Tree",
		})

		m.treeNodesTotal = m.factory.NewGauge(prometheus.GaugeOpts{
			Name: "jmt_tree_nodes_total",
			Help: "Total number of nodes in the tree",
		})

		m.versionsStored = m.factory.NewGauge(prometheus.GaugeOpts{
			Name: "jmt_versions_stored",
			Help: "Number of versions currently stored",
		})

		m.dbLiveBytes = m.factory.NewGauge(prometheus.GaugeOpts{
			Name: "jmt_db_live_bytes",
			Help: "Total live data size in the database in bytes",
		})
	})
}

// JMT Operation Metrics
func (m *PrometheusMetrics) RecordCommit(duration float64, batchSize int) {
	m.commitsTotal.Inc()
	m.commitLatency.Observe(duration)
	m.batchSize.Observe(float64(batchSize))
}

func (m *PrometheusMetrics) RecordOperation(opType string) {
	m.operationsTotal.WithLabelValues(opType).Inc()
}

func (m *PrometheusMetrics) RecordLookup(duration float64, found bool) {
	m.lookupLatency.Observe(duration)
	if found {
		m.operationsTotal.WithLabelValues("lookup_hit").Inc()
	} else {
		m.operationsTotal.WithLabelValues("lookup_miss").Inc()
	}
}

// Proof Metrics
func (m *PrometheusMetrics) RecordProofGeneration(duration float64, proofType string, proofSize int) {
	m.proofGenerationsTotal.WithLabelValues(proofType).Inc()
	m.proofGenerationLatency.Observe(duration)
	m.proofSizeBytes.Observe(float64(proofSize))
}

func (m *PrometheusMetrics) RecordProofValidationFailure() {
	m.validationFailures.Inc()
}

// Database Metrics
func (m *PrometheusMetrics) RecordHashOperation() {
	m.hashOperationsTotal.Inc()
}

func (m *PrometheusMetrics) RecordDBRead() {
	m.dbReadsTotal.Inc()
}

func (m *PrometheusMetrics) RecordDBWrite() {
	m.dbWritesTotal.Inc()
}

// Error Metrics
func (m *PrometheusMetrics) RecordError(errorType string) {
	m.errorsTotal.WithLabelValues(errorType).Inc()
}

// Tree State Metrics
func (m *PrometheusMetrics) UpdateTreeHeight(height int) {
	m.treeHeight.Set(float64(height))
}

func (m *PrometheusMetrics) UpdateTreeNodeCount(count int) {
	m.treeNodesTotal.Set(float64(count))
}

func (m *PrometheusMetrics) UpdateVersionCount(count int) {
	m.versionsStored.Set(float64(count))
}

func (m *PrometheusMetrics) UpdateDatabaseSize(bytes int64) {
	m.dbLiveBytes.Set(float64(bytes))
}

// Ensure PrometheusMetrics implements JMTMetrics interface
var _ JMTMetrics = (*PrometheusMetrics)(nil)
