package commands

import (
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/neutral/proofbox/pkg/proof"
	"github.com/spf13/cobra"
)

// verifyCmd represents the verify command
var verifyCmd = &cobra.Command{
	Use:   "verify <proof-file>",
	Short: "Verify a Merkle proof",
	Long: `Verify a Merkle proof generated by the prove command.
The proof file should be in JSON format as output by the prove command.`,
	Args: cobra.ExactArgs(1),
	RunE: runVerify,
}

func init() {
	rootCmd.AddCommand(verifyCmd)
}

func runVerify(cmd *cobra.Command, args []string) error {
	// Read proof file
	proofFile := args[0]
	
	// Validate file path
	if err := validatePath(proofFile); err != nil {
		return fmt.Errorf("invalid proof file path: %w", err)
	}
	
	// Check file size
	if err := validateFileSize(proofFile, maxImportFileSize); err != nil {
		return fmt.Errorf("proof file too large: %w", err)
	}
	
	file, err := os.Open(proofFile)
	if err != nil {
		return fmt.Errorf("failed to open proof file: %w", err)
	}
	defer file.Close()

	data, err := io.ReadAll(file)
	if err != nil {
		return fmt.Errorf("failed to read proof file: %w", err)
	}

	// Parse proof data
	var proofData map[string]interface{}
	if err := json.Unmarshal(data, &proofData); err != nil {
		return fmt.Errorf("failed to parse proof file: %w", err)
	}

	// Get encoded proof
	encodedStr, ok := proofData["encoded"].(string)
	if !ok {
		return fmt.Errorf("missing or invalid 'encoded' field in proof file")
	}

	encodedProof, err := hex.DecodeString(encodedStr)
	if err != nil {
		return fmt.Errorf("failed to decode proof: %w", err)
	}

	// Decode proof
	codec := proof.NewProofCodec()
	merkleProof, err := codec.Decode(encodedProof)
	if err != nil {
		return fmt.Errorf("failed to decode proof: %w", err)
	}

	// Verify proof
	verifier := proof.NewVerifier()
	err = verifier.Verify(merkleProof)

	result := map[string]interface{}{
		"key":       proofData["key"],
		"version":   merkleProof.Version,
		"root_hash": hex.EncodeToString(merkleProof.RootHash[:]),
		"type":      proofTypeToString(merkleProof.Type),
	}

	if err == nil {
		result["status"] = "valid"
		result["message"] = "Proof is valid"
		
		// Add value for inclusion proofs
		if merkleProof.Type == proof.ProofTypeInclusion {
			result["value"] = string(merkleProof.Value)
			if verboseMode {
				result["value_hex"] = hex.EncodeToString(merkleProof.Value)
			}
		}
	} else {
		result["status"] = "invalid"
		result["message"] = fmt.Sprintf("Proof is invalid: %v", err)
	}

	return outputResult(result)
}